### ISSUE TITLE
Novo release 1.0b2

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/brasil.gov.portlets#3]
@winstonf88 você poderia gerar um release desse produto para adicioná-lo ao IDG 1.1.4? É necessário alterar algumas pinagens para a build passar.

**Comment by idgserpro** [comment]
@hvelarde @winstonf88 poderiam nos auxiliar com a geração de um novo release?

**Comment by hvelarde** [comment]
tem testes falhando; não posso fazer release até isso ser consertado:

https://travis-ci.org/plonegovbr/brasil.gov.portlets/builds/134611850

**Comment by idgserpro** [comment]
Acredito que o PR https://github.com/plonegovbr/portalpadrao.release/pull/9 deva ser mesclado, o diretório alterado de "1.1.4-pending" para "1.1.4", e modificarmos a linha no buildout.cfg de brasil.gov.portlets onde referenciamos "1.1.4-pending" para "1.1.4", antes da geração do release.

Com a mesclagem do PR, e a geração do novo release, também precisamos pinar no versions.cfg de portalpadrao.release para esse novo release de brasil.gov.portlets.

**Comment by idgserpro** [comment]
Efetuando o merge de https://github.com/plonegovbr/brasil.gov.portlets/pull/7, pode criar uma tag aqui no github e um release no pypi.

**Comment by hvelarde** [comment]
release feito: https://pypi.python.org/pypi/brasil.gov.portlets/1.0rc1
