### ISSUE TITLE
Problema com Portlet de Calendário Extendido usando a Agenda Diária

### ISSUE THREAD

**Issue by fabionoki** [plonegovbr/brasil.gov.portlets#4]
Olá Pessoal,

Eu estou utilizando o portlet de calendário extendido para mostrar a
agenda diária e os compromissos, porém sempre que se é cadastrado uma
agenda diária e compromissos para o primeiro dia de o mês (por
exemplo: 1º de Junho), os dias do mês anterior (voltando ao exemplo, o
mês em questão seria o mês de maio) se comporta como se houve
cadastrado agenda diária para todos os dias deste mês, mesmo não tendo
sido cadastrado, enfim os dias no calendário ficam com links (que é o
comportamento padrão quando se é cadastrado uma agenda diária), porém
ao clicar é direcionado a uma página de erro, dizendo que a página não
existe.
Não sei se fui claro na explicação, mas eu gostaria de saber se já
aconteceu ou acontece isso com mais alguém, e se a correção é algo
muito complexo?
A versão do portal padrão em uso é 1.1.3 e Agenda de Membros do
Governo Brasileiro 1.0, Plone 4.3.3 e Python 2.7.6, rodando no Linux 14.04, mas já testei em outras versões mais recentes do Linux e obtive o mesmo problema.

**Comment by idgserpro** [comment]
@fabionoki o portlet de calendário está implementado no [brasil.gov.agenda](https://github.com/plonegovbr/brasil.gov.agenda). Favor abrir o relato lá.

**Comment by fabionoki** [comment]
ok, abrirei o relato lá

Obrigado
